version: '3'
services:
  api:
    build: ./api
    ports:
      - 3000:3000
    depends_on:
      - users-service
      - transactions-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672

  users-service:
    build: ./users-service
    depends_on:
      - rabbitmq
      - db
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:postgres@db:5432/loomi-users-service?schema=public

  transactions-service:
    build: ./transactions-service
    depends_on:
      - rabbitmq
      - db
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:postgres@db:5432/loomi-transactions-service?schema=public

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'

volumes:
  dbdata:

